spring:
#  profiles.active: local
  data:
    mongodb:
      uri: mongodb://host.docker.internal:27017/mySpringBootPractise

management:
  endpoints:
    web:
      exposure:
        include: mappings
springdoc:
  swagger-ui:
    path: "/swagger-ui.html"